;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        cua-cut-region
        cua-paste
        cua-scroll-down
        helm-M-x
        org-self-insert-command
        save-some-buffers
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-visual-line
        eyebrowse-switch-to-window-config-1
        god-mode-all
        mc/mark-all-in-region
        ))
