;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-cut-region
        cua-paste
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-visual-line
        eyebrowse-switch-to-window-config-1
        god-mode-all
        ))
